### ISSUE TITLE
Problème en runnant le repo

### ISSUE THREAD

**Issue by arnaudhuc** [davidvenin/react-redux-example#1]
Salut ,

Après plusieurs difficulté pour installé le repo (mac osx el capitan) je lance le server (npm start) mais La page localhost ne fonctionne pas

localhost n'a envoyé aucune donnée.

j'attache le fichier de log de ma commande 
[log.txt](https://github.com/davidvenin/react-redux-example/files/344588/log.txt)

**Comment by davidvenin** [comment]
Closed : j'ai update le port dans la config au cas où le port par défaut serait déjà utilisé dans vos config.
